### ISSUE TITLE
Prediction do not show anything on satellite

### ISSUE THREAD

**Issue by maherkarim** [weiji14/nz_convnet#1]
Hi,
Thank you for this great effort.
after following the mentioned steps, I tried to run !python ../predict.py 512

I used the same URL mentioned in the documentation, but nothing happened!

can you please tell me how to show the viewer which show the extracted building footprints

Thanks
Maher

**Comment by weiji14** [comment]
Hi,

Sorry for the late reply. Can you tell me how you are running the `!python ../predict.py 512 ` command?  If I remember correctly, that only works inside of a **local** jupyter notebook instance, i.e. not via Binder or some online server.

Alternatively, if you `cd` into the project folder and run `python predict.py`, does a window pop up?

**Comment by weiji14** [comment]
Closing stale issue. Feel free to reopen if necessary.
